[package]
name = "rustodo"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
crossterm = "0.28.1"
dirs = "6.0.0"
rusqlite = "0.34.0"
sqlite = "0.36.2"
tabled = "0.18.0"
uuid = { version = "1.15.1", features = ["v4"] }
